apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-yapw
  labels:
    team: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-yapw
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-yapw
    spec:
      containers:
      - name: frontend-yapw
        image: nikunj3011/yapwwebsite
        imagePullPolicy: Always
        # livenessProbe:
        #   httpGet:
        #     path: /Video/Index
        #     port: 8080
        #   timeoutSeconds: 5
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        # readinessProbe:
        #   initialDelaySeconds: 30
        #   httpGet:
        #     path: /Video/Index
        #     port: 80
        resources:
          limits:
            # cpu: "0.35"
            # memory: 300Mi
          requests:
            # cpu: "0.35"
            # memory: 300Mi
        ports:
        - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: frontendsrv-yapw
spec:
  type: ClusterIP
  selector:
    app: frontend-yapw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontendlb-yapw
spec:
  type: LoadBalancer
  selector:
    app: frontend-yapw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

# http://localhost/swagger/index.html