apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-yapw
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-yapw
  template:
    metadata:
      labels:
        app: backend-yapw
    spec:
      containers:
      - name: backend-yapw
        image: nikunj3011/yapwapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          
---
apiVersion: v1
kind: Service
metadata:
  name: backendsrv-yapw
spec:
  type: ClusterIP
  selector:
    app: backend-yapw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backendlb-yapw
spec:
  type: LoadBalancer
  selector:
    app: backend-yapw
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081

# http://localhost/swagger/index.html